### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by codyrioux** [ianwessen/ufcPredictor#1]
It looks like I carelessly implemented some higher order functions in the main server file: https://github.com/ianwessen/ufcPredictor/blob/master/server.js#L7-L8 without properly testing them.

We require a unit testing framework to ensure correctness across at least some portion of the code base. I'm assigning this one to you, ideally we'll use the same unit testing framework and build tool you're using at work to implement and run the tests respectively.

**Comment by codyrioux** [comment]
Also we're going to need you to write the tests for `compose` and `curry` as I'm currently playing the role of cowboy and don't test anything.

**Comment by ianwessen** [comment]
**Update:** Testing suite added (Mocha and Chai). Working on writing tests. Will close issue when successful tests produced.

**Comment by codyrioux** [comment]
Awesome, which tool is used to run the tests. Do you have a build tool like yeoman at work?

**Comment by ianwessen** [comment]
We’re using Chai paired with Mocha as our testing suite. I’ve created a test/ dir in the root for my testing. There are little stubs of tests as placeholders.

I’m not sure what our build system is, but that’s a definite next step. I’ve worked with gulp a lot for personal projects, but I’ll find out today more about how our build system at SketchDeck works and I’ll implement that as well.
